polls/urls.py
from django.urls import path

from .views import  *

from django.contrib.auth.views import logout

from polls.chart import pogoda_chart


urlpatterns = [
    path('pogoda/wykres/', pogoda_chart.chart, name='chart'),
    path("pogoda/przegladaj/", przegladajListView.as_view(), name="przegladaj"),
    path("pogoda/zaloguj/", login,{'template_name': 'zaloguj.html'}, name="zaloguj"),
    path('pogoda/logout/', logout, {'next_page': '/pogoda'}, name="logout"),
    path("pogoda/rejestracja/", register, name="rejestracja"),
    path("pogoda/", index, name="index"),
    path("pogoda/dokumentacja/", dokumentacja, name="dokumentacja"),

]

pollsapi/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, re_path

urlpatterns = [
    re_path(r'^', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User


class Pogoda(models.Model):
    data = models.DateField()
    czas = models.TimeField()
    miejsce = models.CharField(max_length=100)
    tmax = models.CharField(max_length=100)
    tmin = models.CharField(max_length=100)
    cisnienie = models.CharField(max_length=100)
    wiatr = models.CharField(max_length=100)
    porywy = models.CharField(max_length=100)
    opad = models.CharField(max_length=100)
    zachmurzenie = models.CharField(max_length=100)
    class Meta:
        unique_together = ('data', 'czas','miejsce')
        index_together = [
            ["data", "czas", "miejsce"],
        ]

    def __str__(self):
        return self.question

polls/views.py
from django.shortcuts import render
import json
# Create your views here.

from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from .models import *
from django.views import generic

from django.contrib.auth.views import login

from polls.chart import pogoda_chart
from django.core.validators import *



def register(request):
    if request.method == 'POST':
        arg_username = request.POST.get("username")
        arg_password = request.POST.get("password")
        arg_email = request.POST.get("email")
        user = User(  email=arg_email,username=arg_username)
        user.set_password(arg_password)
        user.save()
    return render(request, 'rejestracja.html')

def validate_pogoda_form(arg_data, arg_czas, arg_miejsce, arg_tmax, arg_tmin, arg_cisnienie, arg_wiatr, arg_porywy, arg_opad, arg_zachmurzenie):
    
    if arg_data == "":
        raise ValidationError('Pole Data jest niepoprawne')

    if arg_czas == "":
        raise ValidationError('Pole Czas jest niepoprawne')
 
    if arg_miejsce == "":
        raise ValidationError('Pole Miejsce jest niepoprawne')
 
    MinValueValidator(-200)(int(arg_tmax))
    MaxValueValidator(200)(int(arg_tmax))

    MinValueValidator(-200)(int(arg_tmin))
    MaxValueValidator(200)(int(arg_tmin))

    if int(arg_tmax) < int(arg_tmin):
        raise ValidationError('Błąd: Tmin jest większy od Tmax')
   
    MinValueValidator(500)(int(arg_cisnienie))
    MaxValueValidator(1500)(int(arg_cisnienie))
 
    MinValueValidator(0)(int(arg_wiatr))
    MaxValueValidator(500)(int(arg_wiatr))
    
    MinValueValidator(0)(int(arg_porywy))
    MaxValueValidator(1000)(int(arg_porywy))

    if int(arg_wiatr) > int(arg_porywy):
        raise ValidationError('Błąd: Wiatr jest większy od Porywy')

    MinValueValidator(0)(int(arg_opad))
    MaxValueValidator(1000)(int(arg_opad))

    MinValueValidator(0)(int(arg_zachmurzenie))
    MaxValueValidator(100)(int(arg_zachmurzenie))
    
def dokumentacja(request):

    return render(request, 'dokumentacja.html')
 
 
def index(request):

    if request.user.is_authenticated and request.method == 'POST':
        arg_data = request.POST.get("data")
        arg_czas = request.POST.get("czas")
        arg_miejsce = request.POST.get("miejsce")
        arg_tmax = request.POST.get("tmax")
        arg_tmin = request.POST.get("tmin")
        arg_cisnienie = request.POST.get("cisnienie")
        arg_wiatr = request.POST.get("wiatr")
        arg_porywy = request.POST.get("porywy")
        arg_opad = request.POST.get("opad")
        arg_zachmurzenie = request.POST.get("zachmurzenie")

        if request.META['CONTENT_TYPE']\
            == "application/json":
            print('Raw Data: "%s"' % request.body)   
            result = json.loads(str(request.body.decode("utf-8")))
            arg_data = result["data"]
            arg_czas = result["czas"]
            arg_miejsce = result["miejsce"]
            arg_tmax = result["tmax"]
            arg_tmin = result["tmin"]
            arg_cisnienie = result["cisnienie"]
            arg_wiatr = result["wiatr"]
            arg_porywy = result["porywy"]
            arg_opad = result["opad"]
            arg_zachmurzenie = result["zachmurzenie"]

        validate_pogoda_form(arg_data, arg_czas, arg_miejsce, arg_tmax, arg_tmin, arg_cisnienie, arg_wiatr, arg_porywy, arg_opad, arg_zachmurzenie)
        pogoda_rec =Pogoda( data=arg_data, czas=arg_czas, miejsce=arg_miejsce, tmax=arg_tmax, tmin=arg_tmin, cisnienie=arg_cisnienie, wiatr=arg_wiatr, porywy=arg_porywy, opad=arg_opad, zachmurzenie=arg_zachmurzenie)
        pogoda_rec.save()

    return render(request, 'index.html')
    
class przegladajListView(generic.ListView):
    model=Pogoda
    template_name = "przegladaj.html"
   
    def get_context_data(self, **kwargs):
        context = super(przegladajListView, self).get_context_data(**kwargs)

        context['miejsce_list'] = Pogoda.objects.values('miejsce').distinct()
        return context


def zaloguj(request):
    m = User.objects.get(username=request.POST['username'])
    if m.password == request.POST['password']:
        request.session['member_id'] = m.id
        return HttpResponse("You're logged in.")
    else:
        return HttpResponse("Your username and password didn't match.")

polls/templates/dokumentacja.html
{% extends "base_generic.html" %}

{% block content %}

<h2>Dokumentacja Strony</h2>

<hr />
<p>Strona została napisana jako projekt numer 2 na techniki internetowe WFIIS.</p>
<p>Autor: Andrzej Mikulec</p>
<p><strong>Tematem projektu jest: System rejestracji pogody.</strong><br />
Technologia:<br />
Serwer: Python3 + Django framework + SQlite3<br />
Przeglądarka: HTML + JavaScript + CSS + IndexedDB<br />
Nieprzyporządkowane: AJAX <br />
</p>

Struktura URI:
<ul>
<li>pogoda/</li>
 <li>pogoda/dokumentacja/</li>
 <li>pogoda/wykres/</li>
 <li>pogoda/przegladaj/</li>
 <li>pogoda/zaloguj/</li>
 <li>pogoda/logout/</li>
 <li>pogoda/rejestracja/</li>
</ul>

<hr />
<h4>Jak uruchomić serwer?</h4>
Aby uruchomić serwer należy wejść do katalogu projektu. Następnie uruchamiamy serwer wywołując poleceniem:<br /><br />
<b style="color: grey">python3 manage.py runserver localhost:8000</b>
<hr />
<h4>Opis projektu</h4>
<p>
System rejestracji pogody pracuje w dwóch trybach:
<ul>
<li><b>Tryb offline</b> Po pierwszym wejsciu na strone znajdujemy się w tym trybie. Tutaj możesz dodać dane do lokalnej bazy danych IndexedDB przeglądarki. Wypełniając prawidłowo pola oraz naciskajac przycisk "Dodaj offline". Rekord został zapisany w bazie. Pod warunkiem że otrzymałeś taki komunikat. W tym trybie panel zawiera kilka zakładek takich jak:
<ul>
    <li>Dodaj dane - jest to strona głowna możesz dodawać rekordy do bazy offline</li>
    <li>Przeglądaj - w tej zakładce możesz zobaczyć zapisane rekordy bazy offline</li>
    <li>Zaloguj - klikając na tą zakłądkę możesz zalgować się do trybu online albo zarejestrować użytkownika</li>
</ul>

<li><b>Tryb online</b> Po zalogowaniu się do trybu online panel uległ drobnej zmianie. Zamiast zakładki "Zaloguj" pojawia się nazwa użytkownika a obok zakładka "Wyloguj". Dodatkowo zmienia się napis na "System rejestracji pogody online". W tym trybie można zrobić dokładnie to samo co w trybie offline tylko że rekordy będą zapisywane albo odczytywane z bazydanych na serwerze SQlite3. Jednym wyjątkiem jest to że tryb ma dodatkową funkcjonalność. Jest nim migracja znajdująca się w zakładce "Dodaj dane". Oraz możliwość generowania wykresów w zakładce "Przeglądaj". Po naciśnieciu przycisku migracja ukażą nam się rekordy bazy IndexedDB które można zaznaczyć i naciskając "migruj zaznaczone" rekord zostanie przesłany do bazy SQLite3 a lokalny rekord zostanie usuniety. Podobnie działa "migruj wszystko" z tym że zrobi to dla wszystkich rekordów. Kolejna rzecz to generowanie wykresów. Przechodząc do zakładki "Przeglądaj" wybieramy miejsowość i naciskamy "Generuj". Zostanie wygenerowany wykres przedstawiajacy maksymalne temeratury w danym mieście na podstawie danych zgromadzonych w bazie SQlite3.



</li>



</ul>




{% endblock %}

polls/templates/fusion.html
<!DOCTYPE html>
<html>
<head>
	<title>Wykres pogodowy</title>

<!-- If you are using downloaded FusionCharts libraries, uncomment the below code   -->
<!--

	{% load static %} 
   	<script type="text/javascript" src="{% static "fusioncharts/fusioncharts.js" %}"></script>
   	<script type="text/javascript" src="{% static "fusioncharts/themes/fusioncharts.theme.fusion.js" %}"></script>
	
-->

   <script type="text/javascript" src="//cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js"></script>
   <script type="text/javascript" src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.fusion.js"></script>

</head>
<body style="font-family:'Helvetica Neue', Arial; font-size: 16px;">
	<h3>{{ chartTitle|safe }}</h3>
	<div id="chart-1">{{ output|safe }}</div>
	<div id="chart-2">{{ output_2|safe }}</div>
	<br/>
	<a href="{% url 'przegladaj' %}">Powrót</a>
</body>
</html>

polls/templates/index.html
{% extends "base_generic.html" %}

{% block content %}


{% if user.is_authenticated %}

<h3>Migracja</h3>
Migruj lokalną bazę danych do bazy na serwerze
<br />
<input type="button" value="migracja" onClick="_upd_list();"/>
<div id="migration_id"></div>
<br />
<br />
<h3>Dodaj Online</h3>
{% endif %} 



{% if user.is_authenticated %}
<form id="pogoda_form" onsubmit="return validateForm(null)" method="post" action="/pogoda/">
{% else %}
<form id="pogoda_form" action="">
{% endif %} 
 
<fieldset>
<table>
      <tr>
        <td>Data:</td>
        <td><input type="date" name="data" value=""></td>
      </tr>
      <tr>
        <td>Godzina:</td>
        <td><input type="time" name="czas" value=""></td>
      </tr>

      <tr>
        <td>Miejsce: </td>
        <td> <input type="text" name="miejsce" value=""></td>
      </tr>
</table>
</fieldset>

<fieldset>
<table>
    
      <tr>
        <td>Tmax:</td>
        <td><input type="number" min="-200" max="200" size="5" name="tmax" value=""></td>
        <td><sup>o</sup>C</td>
      <tr>
        <td>Tmin:</td>
        <td><input type="number" min="-200" max="200" size="5"  name="tmin" value=""></td>
        <td><sup>o</sup>C</td>
      </tr>

      <tr>
        <td>Ciśnienie:</td>
        <td><input type="number" min="500" max="1500" size="5"  name="cisnienie" value=""></td>
        <td>hPa</td>
      </tr> 

       <tr>
        <td>Wiatr:</td>
        <td><input type="number" min="0" max="500" name="wiatr" value=""></td>
        <td>km/h</td>
      </tr>

      <tr>
        <td>Porywy:</td>
        <td><input type="number" min="0" max="1000" size="5" name="porywy" value=""></td>
        <td>km/h</td>
      </tr>
    
      <tr>
        <td>Opad:</td>
        <td><input type="number" min="0" max="1000" size="5" name="opad" value=""></td>
        <td>mm</td>
      </tr>

      <tr>
        <td>Zachmurzenie:</td>
        <td><input type="number" min="0" max="100" size="5" name="zachmurzenie" value=""></td>
        <td>%</td>
      </tr>

</table>
    </fieldset>
        <br><br>

{% if user.is_authenticated %}
<input type="submit" value="Dodaj online">
 {% csrf_token %}
{% else %}
        <input type="button" value="Dodaj offline" onClick="validateForm(this.form);">
{% endif %} 


</form> 



{% endblock %}

polls/templates/przegladaj.html
{% extends "base_generic.html" %}

{% block content %}


{% if user.is_authenticated %}
    {{chart}}

<form method="post" action="/pogoda/wykres/">
{% csrf_token %}
<h4>Generuj wykres</h4>

<div id=chart_sel>
<script>


function select_chart(){
  document.getElementById("chart_sel").innerHTML ="";
  document.getElementById("chart_sel").innerHTML +=
`
    {% if pogoda_list %}
    miejscowosc:<br /><select name="miejsce">

      {% for pogoda in miejsce_list %} 
      
        <option value="{{pogoda.miejsce}}">{{pogoda.miejsce}}</option>  

      {% endfor %}

    </select>
      {% endif %} 
`}
select_chart();


</script>



</div>
<br />
<input type="submit" value="Generuj"/> 
</form>

<br />

<h4>Podgląd rekordów bazy</h4>

     <input type="button" value="Pokaz bazę" onClick="onload=select_sqlite()">

{% else %}
 
        <input type="button" value="Pokaz bazę" onClick="onload=select_indexdb()">
{% endif %} 

  
    <fieldset>

   <div id="field_txt">

   </div>
    </fieldset>
 
{% endblock %}

polls/templates/rejestracja.html
{% extends "base_generic.html" %}


{% block content %}



   </fieldset>
       <center>
       <h3>Stwórz Użytkownika</h3>
       <form method="POST">
       <fieldset style="width: 25%;">
       <legend>Rejestracja</legend>
       {% csrf_token %}
       użytkownik:<input type="text" name="username"/>
       email:<input type="email" name="email"/>
       hasło:<input type="password" name="password"/>
        <br>
        <br>
        <button type="submit">Stwórz</button>


   </fieldset>
       </form>
       </center>



{% endblock %}

polls/templates/zaloguj.html
{% extends "base_generic.html" %}


{% block content %}


{% if user.is_authenticated %}

Uzytkownik jest juz zalogowany
{% else %} 
   </fieldset>
       <center>
       <h3>Zaloguj</h3>
       <form method="POST">
       <fieldset style="width: 25%;">
       <legend>tryb online:</legend>
       {% csrf_token %}
       {{ form }}
        <br>
        <a href="{% url 'rejestracja' %}">Stwórz użytkownika</a>
        <br>
        <button type="submit">Zaloguj</button>


       </fieldset>
       </form>
       </center>

{% endif %} 


{% endblock %}